services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_management_system
    networks:
      - library-management-system-network

networks:
  library-management-system-network:
    driver: bridge