services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_management_system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_management_system"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - library-management-system-network

  library-management-system-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-management-system-api
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgres # We use the service name as the host in Docker Compose but in the local environment, it will be the actual host from the .env file.
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${API_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - library-management-system-network

networks:
  library-management-system-network:
    driver: bridge